name: "機能追加の要望"
title: "[機能追加] タイトルを記入"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## 機能追加の要望
        このテンプレートに沿って、追加してほしい機能の詳細をご記入ください。
        できるだけ具体的な目的、背景、動作イメージ、影響範囲、優先度などを記述してください。
  - type: input
    id: feature-name
    attributes:
      label: 追加してほしい機能の名前
      description: 機能の簡潔な名称を入力してください
      placeholder: 例: タスク管理機能
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 機能の説明
      description: 追加してほしい機能の目的、背景、動作イメージなど、具体的な内容を記述してください
      placeholder: 例: ユーザーがタスクの追加、編集、削除ができ、期限を設定できる機能。これによりタスク管理がより効率的になります。
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の実装優先度を選択してください
      options:
        - label: 高
          value: high
        - label: 中
          value: medium
        - label: 低
          value: low
  - type: checkboxes
    id: impacted-areas
    attributes:
      label: 影響範囲
      description: この変更が影響を与える可能性のあるシステムコンポーネントを選択してください（複数選択可）
      options:
        - label: UI/UX
          value: ui_ux
        - label: API
          value: api
        - label: データベース
          value: database
        - label: インフラ/CI/CD
          value: infrastructure
        - label: その他
          value: others
  - type: textarea
    id: additional-info
    attributes:
      label: その他の情報 / コメント
      description: この機能に関連する背景や参考情報、追加のコメントなどがあればご記入ください
      placeholder: 例: 他プロジェクトでの事例や参考URLなど