 name: Prisma Migrate Deployment

 on:
   push:
     branches:
       - main

 jobs:
   prisma-migrate:
     runs-on: ubuntu-latest

     steps:
       - name: チェックアウト
         uses: actions/checkout@v2

       - name: Node.js のセットアップ
         uses: actions/setup-node@v3
         with:
           node-version: 16

       - name: 依存関係のインストール
         run: npm ci

       - name: Prisma Generate
         run: npx prisma generate

       - name: Prisma Migrate Deploy
         run: npx prisma migrate deploy
         env:
           DATABASE_URL: ${{ secrets.DATABASE_URL }}

       - name: Supabase Migration Deploy
         run: npx supabase migration deploy
         env:
           SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
           SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}